spring:
  application:
    name: fetch
server:
  port: 19093

minio:
  url: http://localhost:9000
  access:
    key: minio
    secret: minioadmin
  buckets:
    downloadBucket: mybucket
    uploadBucket: update-bucket  # 수정된 부분

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버 URL
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기

#data-server:
#  url: localhost:19095
#
#cdn-server:
#  url: http://localhost:19096/cdn