spring:
  application:
    name: resize

  data:
    redis:
      host: localhost # Redis 서버의 호스트명
      port: 6379       # Redis 서버 포트


  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB # 최대 파일 사이즈
      max-request-size: 1GB # 최대 요청 사이즈

server:
  port: 19099



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

minio:
  url: http://localhost:9000
  access:
    key: minio
    secret: minioadmin
  buckets:
    downloadBucket: mybucket
    uploadBucket: update-bucket  # 수정된 부분

cdn-server:
  url: http://localhost:19096/cdn
