spring:
  application:
    name: resize
#  kafka:
#    bootstrap-servers: kafka:29092
#    consumer:
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          deserializer:
#            key:
#              delegate:
#                class: org.apache.kafka.common.serialization.StringDeserializer
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#          json:
#            type:
#              mapping:
server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

minio:
  url: http://minio:9000
  access:
    key: minio
    secret: minioadmin
  buckets:
    uploadBucket: update-bucket

cdn-server:
  url: http://localhost:19096/cdn
